### ISSUE TITLE
Question about weak self

### ISSUE THREAD

**Issue by caijunjieNick** [mehrankmlf/SecurePacketEnvelope#2]
Hello, recently i found your repo, it is so awesome. i just have a question about using weak self in code 
` private func bindViewModel() {
        viewModel?.fullNameMessagePublisher
            .receive(on: RunLoop.main)
            .sink { [weak self] text in
                
                guard let `self` = self, let textField = self.contentView?.txtFullName else {
                    return
                }
                
                if text != "" {
                    self.contentView?.txtFullName.addRightView(txtField:  textField, str: "")
                } else {
                    self.contentView?.txtFullName.addRightView(txtField:  textField, str: "👍🏻")
                }
            }.store(in: &cancellables)
        
        viewModel?.formValidation
            .map { $0 != nil}
            .receive(on: RunLoop.main)
            .sink(receiveValue: { (isEnable) in
                if isEnable {
                    self.contentView?.btnEncrypt.isEnabled = true
                    return
                } else {
                    self.contentView?.btnEncrypt.isEnabled = false
                }
                self.contentView?.btnEncrypt.isEnabled = false
            })
            .store(in: &cancellables)
    }`
Why do u use weak self in the first sink but not in  the second sink? 
I am a new man about this, so i hope to get some guide. Thanks

**Comment by mehrankmlf** [comment]
Hi, In the first sink, [weak self] is used to avoid potential retain cycles, ensuring safe memory management. In the second sink, it's not used but it's recommended for consistency and safety. It's a good practice to use [weak self] whenever referencing self inside closures to prevent memory leaks. so i will make that part safe. thanks for informing me .

**Comment by caijunjieNick** [comment]
@mehrankmlf thanks for reply :)

**Comment by caijunjieNick** [comment]
From your repo, i learned not just using crypto tools and also mvvm. I really appreciate it.

**Comment by mehrankmlf** [comment]
@caijunjieNick Oh, that's great to hear! I hope my open source projects can help you on your journey.
